[project]
name = "kriel-2025-quokka-mhd"
version = "0.1.0"
description = "magnetising quokka code paper"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    "yt>=4.4.1",
]

[tool.pyright]
include = ["scripts"]
